spring:
  logging:
  level:
    ROOT: DEBUG
    org.springframework: DEBUG
    com.trade: DEBUG

  main:
    banner-mode: off
    web-application-type: none

  batch:
    job:
      enabled: true

server:
  port:8081

cassandra:
  entity:
    keyspace: entity
    contactPoints: localhost
    port: 9042
    localDataCenter: datacenter1
    schemaAction: CREATE_IF_NOT_EXISTS
    basePackages: com.trade.entity

batch:
  swiftparty:
    job-name: swiftparty
    location-pattern: classpath:batch/party/swiftparty/GB.json
    #location-pattern: @classpath:batch/party/swiftparty/*.json
    exit-on-completion: true

#TODO move thisto rest client
restclient:
  entity:
    uri: http://localhost:8081
